---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    # Prevent Apt cache errors
    - name: "Refresh Apt cache"
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts["pkg_mgr"] == "apt"
      changed_when: false  # Breaks idempotency test

    # https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
    - name: Wait for systemd to complete initialization. # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 2
      when: ansible_facts["service_mgr"] == 'systemd'
      changed_when: false
      failed_when: false

    # https://github.com/rocky-linux/sig-cloud-instance-images/issues/56#issuecomment-2676249917
    - name: Check if /etc/shadow is readable
      ansible.builtin.stat:
        path: /etc/shadow
      register: shadow_stat

    - name: Ensure /etc/shadow isn't unreadable
      ansible.builtin.command: chmod 0400 /etc/shadow
      when: ansible_os_family == 'RedHat' and shadow_stat.stat.mode != '0400'
      changed_when: true

  tasks:
    - name: "Include x86_39.rke2"
      ansible.builtin.include_role:
        name: x86_39.rke2
      vars:
        rke2_auto_cluster: false

...
