---
name: Molecule Test
"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies.
        run: pip3 install -r requirements.txt

      - name: Install Ansible dependencies.
        run: ansible-galaxy install -r requirements.yml

      - name: Run molecule
        run: "molecule test"

...
